"""Generate the Argus logo assets and the embeddable email data-URI.

Run when the mark changes:  python tools/gen_logo.py
Pillow is a dev-only dependency (requirements-dev.txt); the runtime uses the
generated base64 in app/branding.py and never needs an image library.

The mark: an all-seeing almond eye (Argus, the hundred-eyed watcher) inside an
orbital ring, with a single probe on the orbit. Amber on dark.
"""

import base64
import math
import os

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
BACKEND = os.path.dirname(HERE)
ASSETS = os.path.join(BACKEND, "assets")
os.makedirs(ASSETS, exist_ok=True)

S = 4
W = 256 * S
AMBER = (255, 176, 0, 255)
AMBER_FAINT = (255, 176, 0, 90)
GREEN = (61, 220, 132, 255)
DARK = (11, 14, 26, 255)


def emblem() -> Image.Image:
    img = Image.new("RGBA", (W, W), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    cx = cy = W / 2

    r_orbit = 104 * S
    d.ellipse(
        [cx - r_orbit, cy - r_orbit, cx + r_orbit, cy + r_orbit],
        outline=AMBER_FAINT,
        width=3 * S,
    )

    # almond eye from two arcs sharing their corner points
    a, b = 72 * S, 40 * S
    R = (a * a + b * b) / (2 * b)
    k = R - b
    lid_w = 11 * S
    d.arc([cx - R, (cy + k) - R, cx + R, (cy + k) + R], 211.9, 328.1, fill=AMBER, width=lid_w)
    d.arc([cx - R, (cy - k) - R, cx + R, (cy - k) + R], 31.9, 148.1, fill=AMBER, width=lid_w)

    # iris ring + pupil
    r_iris = 26 * S
    d.ellipse([cx - r_iris, cy - r_iris, cx + r_iris, cy + r_iris], outline=AMBER, width=8 * S)
    r_pupil = 10 * S
    d.ellipse([cx - r_pupil, cy - r_pupil, cx + r_pupil, cy + r_pupil], fill=AMBER)

    # probe on the orbit, upper-right
    ang = math.radians(-45)
    px, py = cx + r_orbit * math.cos(ang), cy + r_orbit * math.sin(ang)
    rp = 11 * S
    d.ellipse([px - rp, py - rp, px + rp, py + rp], fill=GREEN)

    return img.resize((256, 256), Image.LANCZOS)


def tile(em: Image.Image) -> Image.Image:
    out = Image.new("RGBA", (256, 256), (0, 0, 0, 0))
    mask = Image.new("L", (256, 256), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, 255, 255], radius=56, fill=255)
    out.paste(Image.new("RGBA", (256, 256), DARK), (0, 0), mask)
    out.paste(em, (0, 0), em)
    return out


def main() -> None:
    em = emblem()
    em.save(os.path.join(ASSETS, "logo.png"))          # transparent, 256
    tile(em).save(os.path.join(ASSETS, "logo_tile.png"))  # dark app icon

    # 128px transparent PNG for email, embedded as a data URI
    email_png = os.path.join(ASSETS, "logo_email.png")
    em.resize((128, 128), Image.LANCZOS).save(email_png)
    with open(email_png, "rb") as f:
        data = base64.b64encode(f.read()).decode()
    uri = f"data:image/png;base64,{data}"

    branding = os.path.join(BACKEND, "app", "branding.py")
    with open(branding, "w", encoding="utf-8") as f:
        f.write('"""Generated by tools/gen_logo.py. Do not edit by hand."""\n\n')
        f.write('# Content-ID for the inline email attachment (Gmail strips data: URLs).\n')
        f.write('LOGO_CID = "argus-logo"\n\n')
        f.write('# For in-browser use (frontend, previews) where data: URIs work.\n')
        f.write(f'LOGO_DATA_URI = "{uri}"\n')
    print(f"wrote assets/ and app/branding.py ({len(data)} b64 chars)")


if __name__ == "__main__":
    main()
